# Literature {#lit-review}

In this study, we have chosen to focus on three specific community resources
that have robust histories of accessibility and spatial analysis: parks, grocery
stores, and libraries. This section first discusses research developing and 
classifying various accessibility measures, followed by a discussion of previous
attempts to measure access to the resources selected for this analysis.

## Developing Access Measures

Accessibility is easily defined as the ability to reach useful destinations [@handy1997],
but this ease in definition belies a wide array of potential quantitative 
descriptions. @dong2006 present a helpful hierarchy of access measures, which we
briefly summarize here.

Among the simplest measures of access is a so-called isochrone measure, which
considers whether a person at position $i$ traveling to a potential destination 
$j$ is within a particular travel time threshold $t^*$. Using this measure, a
person has access to the resource if $t_{ij} < t_*$. Sometimes it is 
possible to access multiple resources within this threshold, in which case a
more continuous score can be defined as 
\begin{equation}
  A_i^{\mathrm{isochrone}} = \sum_{j \in J} \delta_{ij}, 
  \mathrm{\ where\ } \delta_{ij} = 
  \begin{cases}
    1, & \text{for } t_{ij} \leq t^*\\
    0, & \text{for } t_{ij} > t^*
  \end{cases} 
  (\#eq:isochrone)
\end{equation}
Variations of this measure include elements like "number of grocery stores 
within 10 minutes" or "density of green space within 5 miles." Strengths of 
this method are its relative simplicity, but it has three central limitations. First,
the threshold $t^*$ must be defined by the researcher for a specific value by
a certain travel mode, and different definitions
can have different policy outcomes [@logan2019]. Second, the binary nature of the
measure belies our understanding of behavior: a four minute and fifty second
trip is not functionally different from a five minute and ten second trip. Finally,
the measure assumes that all options in the choice set $J$ are of equivalent 
quality.

Extensions to this basic framework relax some of these constricting assumptions. 
A gravity model accessibility measure
\begin{equation}
  A_i^{\mathrm{gravity}} = \sum_{j \in J} S_j * f(t_{ij}, \beta)
  (\#eq:gravity)
\end{equation}
considers the "size" of the destination $S_j$ as well as a continuous travel 
impedance function that decreases the impact of further destinations. The parameters
of this impedance function can be calibrated to match the observed trip length
distribution of a survey or other data, or a basic distance decay function without
parameters can be used. Additionally, if no other information on the "size" or 
attractiveness of the destinations is available, then $S_j = 1$.

Activity-based or utility-based measures rely on location choice theory, where 
the probability of choosing a destination is a function of the destination's 
attributes weighted against the travel impedance to reach it. The mathematical 
details of this measure are described below in Section \@ref(framework), but the 
measure relies on understanding how the attributes of a destination $X_j$ affect
the utility $V_{ij}$ of a person at origin $i$ selecting that destination
\begin{equation}
V_{ij} = X_{ij}\beta
  (\#eq:simple-utility)
\end{equation}
One potential obstacle to developing utility-based accessibility measures is
obtaining sufficient data on which to estimate the utility preference parameters $\beta$.
High-quality household surveys that reveal activity locations are most commonly
used for this purpose in general travel demand modeling, but such surveys typically
group many infrequent discretionary trips into catch-all categories [@nchrp716].

In the last several years, various commercial data products developed from
mobile device and location-based services (LBS) data have entered common use in
transportation planning activities. Applications or websites that serve mobile 
content based on a users location will log this location information and 
sell the data to commercial third-party aggregators. These aggregators in turn will weight 
and anonymize the data before selling the prepared datasets to transportation 
planning agencies. These LBS datasets typically contain
vehicle or person flows between spatially defined zones, sometimes segmented by
inferred transportation mode, time of day, day of week, or imputed trip purpose.
These datasets have been shown to accurately reflect visits to recreation areas
and other land uses [@monz2019], and are becoming a common part of transportation
planning practice [@naboulsi2016; @tcrp138]. In recent years, researchers have
begun developing methods to estimate destination choice models (and their
related utility parameters) from passive data. @zhu2018 developed a method to
estimate a destination choice model for taxi trips in Shanghai, relying on the
scale of the GPS dataset to estimate a robust model. @alamedaparks use
location-based services data for park visitors in Alameda County, California to
estimate a destination choice model, and then apply that model to examine
utility-based park accessibility and equity.


## Access to Parks, Grocery Stores, and Libraries 

Parks and other open spaces are frequently understood to provide mental and physical
health benefits to the members of the community who use them [@bedimo2005], but
specific evidence of a link between access and these benefits is somewhat mixed, 
perhaps due to a wide variety of accessibility measures used in various studies
[@bancroft2015association]. Most use some form of isochrone-based measure. For example, 
@neusel2016 developed a county-level green space density measure for the entire United
States based on the percentage of developed green space in each county.
A popular measure called ParkScore [@parkscore2019] uses the share of a
population that lives within a 10-minute walk of a park to provide a metropolitan-level
accessibility score. Some studies have shown that metropolitan areas with a higher
ParkScore have better health outcomes [@rigolon2018], but this finding has not 
been satisfactorily reproduced for neighborhoods within a metropolitan region. 
@kacynski2016 developed ParkIndex, a
measure that gives extra weight to neighborhoods near high-quality parks by
incorporating park choice preferences determined from a user survey; some of the
usefulness of this measure is limited by only weighting neighborhoods within 1
mile of a park rather than being applied continuously across the region as a utility-based 
access measure. @macfarlane2020 constructed a utility-based access to parks
measure derived from an earlier park choice survey [@kinnell2006], and showed a
positive relationship between this measure and health outcomes that does not
appear to exist when using the ParkScore isochrone access measure.

The accessibility of grocery stores to low-income or other disadvantaged
communities has been a similarly frequent topic in the academic literature; 
both in terms of identifying the existence of so-called "food deserts" as well 
as correlating these deserts with measures of well-being. The U.S. Department of
Agriculture (USDA) defines food deserts for their own purposes as low-income census tracts
where a certain threshold of people live more than a mile from the nearest 
grocery store, or a shorter threshold if automobile ownership is low [@usdafara].
Most other researchers have adopted similar definitions of access. For example,
@morland2002 use the number of grocery stores in the same census tract, @algert2006 
used the share of households within 0.8 kilometers of a store, and @hamidi2020
uses the USDA measures directly. 
In conflict with these simplistic definitions are 
a number of studies suggesting that the nearest grocery store is not necessarily
where people --- including low-income people --- obtain their food 
[@recker1978; @clifton2004; @aggarwal2014]. @wood2016 addressed this shortcoming
by considering a gravity-derived accessibility measure, weighting the number of 
opportunities against a continuous travel time function. Other more recent research
has suggested that what matters 
is not home accessibility as much as location of a store within a time-space construction
of a person's daily activities [@widener2015spatiotemporal; @chen2021effects].

Libraries provide important educational and social opportunities for community
members through computer facilities, reference materials, and special programs 
[@maxwell2008libraries; @barclay2017space]. Libraries can also be used to 
enhance physical and emotional well-being in a community through public 
initiatives [@philbin2019]. Though perhaps not as commonly studied as either 
parks or libraries, a few recent efforts have examined the spatial distribution
of libraries and socioeconomic disparities in access. @allen2019 measured the 
gap in travel time to the nearest library by car and by public transit, showing
that transit-dependent communities were considerably disadvantaged. @cheng2021
applied travel time thresholds to examine the share of communities in Hong Kong
that lacked access. @guo2017 also measured library access disparities in  Hong Kong,
using two different travel-time focused measures. None of the measures we could 
find considered other attributes of the library beyond its proximity, even though
these addtional features play a strong role in the library's role in community building
[@barclay2017space].

Certainly there are other community resources that warrant consideration;
@ermagun2020 consider a multiple-resource gravity accessibility measure that
includes schools, jobs, and hospitals in addition to the three that have been used here. 
Churches, museums, or various other facilities might be relevant elements
in shaping the quality of life in a community.  Regardless of what resources are  
selected, it is clear that existing accessibility practice considers spatial
proximity as paramount, and quality of the destination as secondary. Further, 
travel times by particular modes are the default measure rather than holistic,
multimodal travel impedance measures. Using utility-based measures for both
travel impedance and for the accessibility measure might provide a more 
complete picture of who can and who cannot access community resources in a region.









